import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("../", import.meta.url));
const result = await build({
  absWorkingDir: root,
  entryPoints: { "hooks/run": "src/hooks/run.ts", "rag/run": "src/rag/cli.ts", "mcp/run": "src/rag/mcp.ts" },
  outdir: resolve(root, "runtime"),
  outExtension: { ".js": ".mjs" },
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  external: ["onnxruntime-node"],
  banner: { js: 'import { createRequire as geistCreateRequire } from "node:module"; const require = geistCreateRequire(import.meta.url);' },
  legalComments: "inline",
  metafile: true,
  write: false,
});
// Standalone installations must retain the notices for code bundled from npm.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.replaceAll("\\", "/").includes("node_modules/")) continue;
  let directory = dirname(resolve(root, input));
  while (dirname(directory) !== directory) {
    const manifestPath = resolve(directory, "package.json");
    const manifest = existsSync(manifestPath) && JSON.parse(readFileSync(manifestPath, "utf8"));
    if (manifest?.name) {
      const files = readdirSync(directory).filter((file) => /^(licen[cs]e|notice)(\.|$)/i.test(file)).sort();
      assert.ok(files.length, `Missing dependency license: ${manifest.name}`);
      packages.set(`${manifest.name}@${manifest.version}`, files.map((file) => readFileSync(resolve(directory, file), "utf8").trim()).join("\n\n"));
      break;
    }
    directory = dirname(directory);
  }
}
const notices = "Third-party code bundled into Geist runtime files.\nGenerated by scripts/build-hooks.mjs; dependency notices follow.\n\n" +
  [...packages].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([name, license]) => `===== ${name} =====\n\n${license}`).join("\n\n") + "\n";
result.outputFiles.push({ path: resolve(root, "runtime/THIRD_PARTY_NOTICES.txt"), text: notices.replace(/\r\n/g, "\n") });
for (const output of result.outputFiles) {
  if (process.argv.includes("--check")) {
    assert.equal(readFileSync(output.path, "utf8").replace(/\r\n/g, "\n"), output.text,
      `Bundle is stale: ${output.path}; run npm run build`);
  } else {
    mkdirSync(dirname(output.path), { recursive: true });
    writeFileSync(output.path, output.text);
  }
}
console.log(process.argv.includes("--check") ? "Geist runtime bundles match their source." : "Built Geist hooks, RAG CLI, and MCP server.");
